project:
  title: "A_SDM"
  execute-dir: project
  output-dir: docs
date: last-modified
execute:
  freeze: auto  # re-render only when source changes
  
toc: true # table of content at beginning of document
toc-location: left
toc_float: TRUE
toc-depth: 3
number-sections: true
highlight-style: pygments

format: 
  html: 
    embed-resources: true
    code-fold: false
    page-layout: article
    grid:
      body-width: 1000px
      margin-width: 50px
    html-math-method: katex # displays equations
  # docx: 
  #   reference-doc: Manuscripts/customreference_nonb.docx
  # pdf:
  #   code-line-numbers: true
  #   geometry: 
  #     - top=20mm
  #     - left=20mm 

bibliography: references.bib
