---
title: "sandbox"
editor: source
---

## Test your stuff
A.  Current speed daily max \[`r factors[2,3]`\] and Inundation time \[`r factors[3,3]`\]: RQ2int optimum is of `r rq_opti$Biomass$maxsdm[1]` gAFDW/m², at `r rq_opti$Biomass$optx1[1]` `r  factors[2,3]` and`r rq_opti$Biomass$optx2[1]` `r factors[3,3]`; RQ2nli optimum is of `r nlrq_opti$Biomass$maxsdm[1]` gAFDW/m², at `r nlrq_opti$Biomass$optx1[1]` `r factors[2,3]` and`r nlrq_opti$Biomass$optx2[1]` `r factors[3,3]`.


B.  Salinity daily range \[`r factors[5,3]`\] and Temperature \[`r factors[6,3]`\]: RQ2int optimum is of `r rq_opti$Biomass$maxsdm[2]` gAFDW/m², at `r rq_opti$Biomass$optx1[2]` `r factors[5,3]` and`r rq_opti$Biomass$optx2[2]` `r factors[6,3]`; RQ2nli optimum is of `r nlrq_opti$Biomass$maxsdm[2]` gAFDW/m², at `r nlrq_opti$Biomass$optx1[2]` `r factors[5,3]` and`r nlrq_opti$Biomass$optx2[2]` `r factors[6,3]`.


C.  Salinity daily range \[`r factors[5,3]`\] and Bathymetry \[`r factors[9,3]`\]: RQ2int optimum is of `r rq_opti$Biomass$maxsdm[3]` gAFDW/m², at `r rq_opti$Biomass$optx1[3]` `r factors[5,3]` and`r rq_opti$Biomass$optx2[3]` `r factors[9,3]`; RQ2nli optimum is of `r nlrq_opti$Biomass$maxsdm[3]` gAFDW/m², at `r nlrq_opti$Biomass$optx1[3]` `r factors[5,3]` and`r nlrq_opti$Biomass$optx2[3]` `r factors[9,3]`.


D.  Mud content \[`r factors[14,3]`\] and Bed shear stress \[`r factors[11,3]`\]: RQ2int optimum is of `r rq_opti$Biomass$maxsdm[4]` gAFDW/m², at `r rq_opti$Biomass$optx1[4]` `r factors[14,3]` and`r rq_opti$Biomass$optx2[4]` `r factors[11,3]`; RQ2nli optimum is of `r nlrq_opti$Biomass$maxsdm[4]` gAFDW/m², at `r nlrq_opti$Biomass$optx1[4]` `r factors[14,3]` and`r nlrq_opti$Biomass$optx2[4]` `r factors[11,3]`.